### PR TITLE
[Docs] Alexwangxiang/t-sne_visualize_doc

### PR DESCRIPTION
**Pull request by alexwangxiang**
## Motivation

My motivation of this PR is to upload t-SNE documentation written by me.

## Modification

I added an English markdown documentation to the t-SNE visualization tool. I will add Chinese documentation of it in the future. Now I only tried to visualize classification models, and I will try to visualize self-supervised models in the future.

### CODE REVIEW

**Comment by Ezra-Yu** [comment]
Please rebase the latest dev branch and add the CN version. By the way, you can use GPT or Claude to help you.

**Comment by Ezra-Yu** [comment]
closed since the main branch has fixed this typo.

**Comment by alexwangxiang** [comment]
> Please rebase the latest dev branch and add the CN version. By the way, you can use GPT or Claude to help you.

我在另一个pr (#1555) 里添加了中文文档，但我对github里如何更新pr不熟，听说能直接更新这个pr (#1551)，请问你知道应该如何操作么？

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @alexwangxiang,

We'd like to express our appreciation for your valuable contributions to the mmpretrain. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Comment by Ezra-Yu** [comment]
> 我在另一个pr (#1555) 里添加了中文文档，但我对github里如何更新pr不熟，听说能直接更新这个pr (#1551)，请问你知道应该如何操作么？

直接放在一个PR(#1555) 中吧。不要分开

**Pull request closed without merging**
