### PR TITLE
Add figures for model zoo

### PR DESCRIPTION
**Pull request by wangruohui**

### CODE REVIEW

**Comment by wangruohui** [comment]
SVG are changed to LFS

**Comment by wangruohui** [comment]
LFS is not permitted if it is not enabled upstream. Thus I amended commits and push only the script.

**Comment by wangruohui** [comment]
CIFAR10-GFLOPS-top-1
CIFAR10-MParams-top-1
ImageNet-GFLOPS-top-1
ImageNet-GFLOPS-top-5
ImageNet-MParams-top-1
ImageNet-MParams-top-5

**Comment by digantamisra98** [comment]
@hellock any updates on this?

**Pull request closed without merging**
