### PR TITLE
docs(build): use python -m pip instead of pip

### PR DESCRIPTION
**Pull request by tpoisonooo**
## Motivation

Fix python requirements install description to avoid Python version problem. They are different:
```shell
(base) khj@khj:~/mmdeploy$ python3 -m pip --version
pip 21.2.4 from /mnt/d/khj/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
(base) khj@khj:~/mmdeploy$ pip --version
pip 22.0.4 from /mnt/d/khj/.local/lib/python3.8/site-packages/pip (python 3.8)
```

same as https://github.com/open-mmlab/mmdeploy/pull/341

### CODE REVIEW

**Comment by mzr1996** [comment]
Sorry but I think the problem is not use `pip` or `python3 -m pip`
Looks you have installed an extra pip for your user. And the path of this extra pip have higher priority.
Normally, the `pip` command will also use the version of your conda.
```shell
~$ whereis pip
pip: /home/mzr/.local/miniconda3/envs/main/bin/pip
```

**Comment by tpoisonooo** [comment]
> 

1. Yes `.local/bin/pip` have higher priority in my env, but `python3 -m pip` always point to the right one.
After `conda` installed, default `pip` linked to `~/.local/bin/pip` while not `~/.miniconda/bin/pip`. It is much more **robust** to configuration error.

2. Many github CI also use `python3 -m pip` instead of  `pip`, for example https://github.com/pybind/pybind11/blob/70a58c577eaf067748c2ec31bfd0b0a614cffba6/.github/workflows/ci.yml#L358

**Comment by tpoisonooo** [comment]
If `python3 -m pip`, newcomers don't have to struggle:

"Why I `pip` installed dependencies but couldn't `import` them ? "

**Comment by fangyixiao18** [comment]
I'm sorry to inform you that the previous master(dev) branch has been abandoned, and therefore, this pull request (PR) based on the master(dev) branch will be closed.

We have integrated the previous mmcls and mmselfsup into a new repo named mmpretrain, and you are welcome to use it.

**Pull request closed without merging**
