### PR TITLE
Create rmnet.py

### PR DESCRIPTION
**Pull request by fxmeng**
## Motivation & Modification

We create [rmnet.py](https://github.com/fxmeng/mmclassification/blob/5e2a41b329deb94ec81c156b6d1daf9a222cb3d5/tools/convert_models/rmnet.py) to this project follow the [issue](https://github.com/fxmeng/RMNet/issues/1#issue-1045412150). In which, a pre-trained ResNet can be equivalently converted to a VGG-like model by:
`python tools/convert_models/resnet2vgg.py ${config_path} ${checkpoint_path} ${save_path}`

### CODE REVIEW

**Comment by mzr1996** [comment]
Thanks for your contribution, we will review it soon.

**Comment by mzr1996** [comment]
Hello, I notice that this tool can convert some of ResNet checkpoints to RMNet checkpoints. But we cannot inference these models with checkpoints only.
Are you willing to continue to finish the RMNet implementation? We will be happy to keep in contact with you. Or we will take over this work.

**Comment by fxmeng** [comment]
> Hello, I notice that this tool can convert some of ResNet checkpoints to RMNet checkpoints. But we cannot inference these models with checkpoints only. Are you willing to continue to finish the RMNet implementation? We will be happy to keep in contact with you. Or we will take over this work.

Hi, I have finished the RMNet implementation following:
https://github.com/fxmeng/mmclassification/blob/4f71510f05505574cff8c6549562d6c6bb6ade27/configs/rmnet/Readme.md

**Comment by mzr1996** [comment]
> > Hello, I notice that this tool can convert some of ResNet checkpoints to RMNet checkpoints. But we cannot inference these models with checkpoints only. Are you willing to continue to finish the RMNet implementation? We will be happy to keep in contact with you. Or we will take over this work.
> 
> Hi, I have finished the RMNet implementation following: https://github.com/fxmeng/mmclassification/blob/4f71510f05505574cff8c6549562d6c6bb6ade27/configs/rmnet/Readme.md

Wow, really thank you, I will check it later.

**Comment by OpenMMLab-Assistant003** [comment]
Hi @fxmeng！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @fxmeng

**Pull request closed without merging**
